<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<PackageId>Sachkov_.NET-Fullstack.Shared.Core</PackageId>
		<Version>0.0.1</Version>
		<PackageDescription>Shared.Core for repository Sachkov_.NET-Fullstack</PackageDescription>
	</PropertyGroup>

	<ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Scrutor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared.Kernal\Shared.Kernel.csproj" />
  </ItemGroup>

</Project>
