<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="Sachkov_.NET-Fullstack.Shared.Framework" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DirectoryService.Contracts\DirectoryService.Contracts.csproj" />
		<ProjectReference Include="..\DirectoryService.Core\DirectoryService.Core.csproj" />
	</ItemGroup>

</Project>
