<Project Sdk="Microsoft.NET.Sdk">



  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Dapper.SqlBuilder" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Sachkov_.NET-Fullstack.Shared.Core" />
    <PackageReference Include="Sachkov_.NET-Fullstack.Shared.Framework" />
    <PackageReference Include="System.Linq.Async" />
  </ItemGroup>



  <ItemGroup>
    <ProjectReference Include="..\DirectoryService.Contracts\DirectoryService.Contracts.csproj" />
    <ProjectReference Include="..\DirectoryService.Domain\DirectoryService.Domain.csproj" />
  </ItemGroup>

</Project>
